import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

import { ReferralLinkCard } from "@/components/referral-link-card";
import { SuperPayoutRequestCard } from "@/components/super-payout-request-card";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function SuperAffiliatorDashboardPage() {
  // Enforce server-side access control to the super affiliator workspace.
  const session = await getServerSession(authOptions);

  if (!session?.user) {
    redirect("/login");
  }

  if (session.user.role !== "super-affiliator") {
    redirect("/dashboard/affiliator");
  }

  // Fetch the supervising account with the affiliators they manage.
  const superAffiliator = await prisma.superAffiliator.findUnique({
    where: { userId: session.user.id },
    include: {
      user: true,
      affiliators: {
        include: {
          user: true,
          leads: true,
        },
        orderBy: {
          user: {
            name: "asc",
          },
        },
      },
    },
  });

  if (!superAffiliator) {
    return (
      <section className="space-y-4 p-6">
        <h1 className="text-2xl font-semibold text-gray-900">Super Affiliator Dashboard</h1>
        <p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          We could not locate your super affiliator profile. Please contact support.
        </p>
      </section>
    );
  }

  // Preload indirect leads generated by the supervised affiliators.
  const indirectLeads = await prisma.student.findMany({
    where: {
      affiliator: {
        superAffiliatorId: superAffiliator.id,
      },
    },
    include: {
      affiliator: {
        include: {
          user: true,
        },
      },
    },
  orderBy: [{ leadStatus: "asc" }, { name: "asc" }],
  });

  const affiliators = superAffiliator.affiliators.map((affiliate) => ({
    id: affiliate.id,
    name: affiliate.user.name,
    email: affiliate.user.email,
    tokenBalance: affiliate.tokenBalance,
    leadCount: affiliate.leads.length,
    admittedCount: affiliate.leads.filter((lead) => lead.leadStatus === "admitted").length,
    referralLink: affiliate.referralLink,
  }));

  return (
    <section className="space-y-8 p-6">
      <header className="space-y-2">
        <h1 className="text-3xl font-semibold text-gray-900">
          Welcome back, {superAffiliator.user.name.split(" ")[0]}
        </h1>
        <p className="text-sm text-gray-600">
          Oversee your affiliator network, track indirect leads, and manage override payouts from one place.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="h-full rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
          <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">Override token balance</p>
          <p className="mt-2 text-3xl font-bold text-emerald-600">
            {superAffiliator.tokenBalance.toLocaleString()} tokens
          </p>
          <p className="mt-1 text-xs text-gray-500">
            Earn 500 tokens for every student admitted through your affiliator network.
          </p>
        </div>
        <ReferralLinkCard
          referralCode={superAffiliator.referralCode}
          shareLinkOverride={`${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/register/affiliator?super=${superAffiliator.referralCode}`}
          title="Affiliator signup link"
          helperText="Share this link to onboard new affiliators under your supervision."
        />
      </div>      <section className="space-y-3">
        <header className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Affiliators under you</h2>
          <span className="text-xs text-gray-500">{affiliators.length} total</span>
        </header>

        <div className="w-full rounded-2xl border border-gray-200 bg-white shadow-sm">
          <div className="w-full overflow-x-auto">
            <table className="w-full min-w-[760px] divide-y divide-gray-200 text-left text-sm">
            <thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500">
              <tr>
                <th className="px-4 py-3">Affiliator</th>
                <th className="px-4 py-3">Tokens</th>
                <th className="px-4 py-3">Leads</th>
                <th className="px-4 py-3">Admitted</th>
                <th className="px-4 py-3">Latest referral</th>
              </tr>
            </thead>
            <tbody>
              {affiliators.length === 0 ? (
                <tr>
                  <td className="px-4 py-6 text-center text-sm text-gray-500" colSpan={5}>
                    No affiliators yet. Share your signup link to start building a network.
                  </td>
                </tr>
              ) : (
                affiliators.map((affiliate) => (
                  <tr key={affiliate.id} className="odd:bg-white even:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="font-medium text-gray-900">{affiliate.name}</div>
                      <div className="text-xs text-gray-500">{affiliate.email}</div>
                    </td>
                    <td className="px-4 py-3 text-gray-700">{affiliate.tokenBalance.toLocaleString()}</td>
                    <td className="px-4 py-3 text-gray-700">{affiliate.leadCount}</td>
                    <td className="px-4 py-3 text-gray-700">{affiliate.admittedCount}</td>
                    <td className="px-4 py-3 text-sm text-sky-600">
                      <a
                        href={`${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/student/${affiliate.referralLink}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:underline"
                      >
                        View student link
                      </a>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="space-y-3">
        <header className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Indirect leads</h2>
          <span className="text-xs text-gray-500">{indirectLeads.length} students</span>
        </header>

        <div className="w-full rounded-2xl border border-gray-200 bg-white shadow-sm">
          <div className="w-full overflow-x-auto">
            <table className="w-full min-w-[720px] divide-y divide-gray-200 text-left text-sm">
            <thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500">
              <tr>
                <th className="px-4 py-3">Student</th>
                <th className="px-4 py-3">Course</th>
                <th className="px-4 py-3">Affiliator</th>
                <th className="px-4 py-3">Status</th>
              </tr>
            </thead>
            <tbody>
              {indirectLeads.length === 0 ? (
                <tr>
                  <td className="px-4 py-6 text-center text-sm text-gray-500" colSpan={4}>
                    Once your affiliators start enrolling students you will track them here.
                  </td>
                </tr>
              ) : (
                indirectLeads.map((lead) => (
                  <tr key={lead.id} className="odd:bg-white even:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="font-medium text-gray-900">{lead.name}</div>
                      <div className="text-xs text-gray-500">{lead.email}</div>
                    </td>
                    <td className="px-4 py-3 text-gray-600">{lead.course}</td>
                    <td className="px-4 py-3 text-gray-600">
                      <div className="font-medium text-gray-900">{lead.affiliator.user.name}</div>
                      <div className="text-xs text-gray-500">{lead.affiliator.user.email}</div>
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-medium ${
                          lead.leadStatus === "admitted"
                            ? "bg-emerald-100 text-emerald-700"
                            : "bg-amber-100 text-amber-700"
                        }`}
                      >
                        {lead.leadStatus}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="space-y-3">
        <header className="flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Request override payout</h2>
          <span className="text-xs text-gray-500">Tokens convert to cash upon approval</span>
        </header>

        <SuperPayoutRequestCard tokenBalance={superAffiliator.tokenBalance} />
      </section>
    </section>
  );
}
